### ISSUE TITLE
请问能解释一下normalize_screen_coordinates的作用吗

### ISSUE THREAD

**Issue by luzzou** [lxy5513/videopose#23]
你好，最近在看VideoPose3D的代码，看到normalize_screen_coordinates这个函数一直不明白是在做什么，小白一只，相机内参里面的"w"和"h"又是对应的什么呢？

**Comment by lxy5513** [comment]
意思是将图片标准化resize到（0-1）之间。训练集是在w=1000,h=1002图片上训练出来的，在inference过程中我尝试了根据图片的大小resize, 但效果没有直接设为w=1000,h=1002好

ps：标准化的作用是加速收敛，提高算法精度。

**Comment by luzzou** [comment]
明白了，非常感谢！

**Comment by ns3new** [comment]
Hello How to solve this issue ? Get an error 

```
outputs/dance.mp4 --- elapsed time: 3.2093143170004623 s
Traceback (most recent call last):
  File "videopose.py", line 164, in <module>
    inference_video('outputs/dance.mp4', 'hr_pose')
  File "videopose.py", line 160, in inference_video
    main(args)
  File "videopose.py", line 79, in main
    keypoints = normalize_screen_coordinates(keypoints[..., :2], w=1000, h=1002)
  File "/home/viz/test/visualization/video-to-pose3D/common/camera.py", line 16, in normalize_screen_coordinates
    assert X.shape[-1] == 2
AssertionErro
```r
